AllCops:
  Exclude:
    - 'bin/*'

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 90
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'spec/spec_helper.rb'
    - 'db/**/*'
    - 'config/**/*'
